import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./Navbar";
import ThemeChanger from "./ThemeChanger";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-bs-theme="dark">
        <ThemeChanger/>
        <Navbar />
        {children}
        <footer className="container pt-3 mt-4 text-body-secondary border-top">
          © 2023
        </footer>
      </body>
    </html>
  );
}
